
package:
  name: zipline-tardis-bundle
  version: 0.1.0

source:
  git_url: git@github.com:phelps-sg/zipline-tardis-bundle.git

build:
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python
    - cython
    - numpy
  host:
    - python
    - cython
    - numpy
    - pip
  run:
    - python>=3.10
    - numpy
    - pandas
#    - pre-commit
#    - blackd
#    - pylint
#    - pytest
#    - pytest-mock
#    - pydrive
#    - mypy
    - zipline-reloaded
    - pyfolio-reloaded
    - tardis-client>=1.3.4
    - tardis-dev
#    - pip
    - ray-default
    - grpcio=1.43
    - fn
    - pykalman
#        - mPyPl
#        - tardis-client
#        - tardis_dev
#        - backtrader


test:
  commands:
    - python -c "import zipline_tardis_bundle"
#  requires:
#    - pip

about:
  home: https://github.com/phelps-sg/zipline-tardis-bundle
  summary: A Zipline bundle for TARDIS data
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - steve-phelps
