
package:
  name: zipline-tardis-bundle
  version: 0.3.6

source:
  path: ../..

build:
  entry_points:
    - install-tardis-bundle = zipline_tardis_bundle.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python
    - cython
    - numpy>=1.22
  host:
    - python
    - cython
    - numpy
    - pip
  run:
    - python>=3.8
    - numpy
    - pandas
    - zipline-reloaded>=3.0.3
    - tardis-client>=1.3.4
    - tardis-dev
    - ray-default>=2.6.3
    - grpcio=1.43
    - fn

test:
  commands:
    - python -c "import zipline_tardis_bundle"

about:
  home: https://github.com/phelps-sg/zipline-tardis-bundle
  summary: A Zipline bundle for TARDIS data
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - steve-phelps
