name: zipline-tardis-bundle
channels:
 - conda-forge
 - mesonomics
dependencies:
 - boa
 - anaconda-client
 - python=3.10
 - numpy
 - pandas
 - pandas-stubs
 - pre-commit
 - blackd
 - pylint=2.17.7
 - pytest
 - pytest-mock
 - mypy
 - zipline-reloaded
 - pip
 - ray-default>=2.6.3
 - grpcio=1.43
 - fn
 - pykalman
 - tardis-client
 - tardis-dev
 - pip:
   - pylint-pytest
   - -e ./
