name: zipline-tardis-bundle
channels:
 - conda-forge
 - mesonomics
dependencies:
 - boa
 - anaconda-client
 - python=3.11
 - numpy
 - pandas
 - pandas-stubs
 - pre-commit
 - blackd
 - pylint
 - pytest
 - pytest-mock
 - mypy
 - zipline-reloaded
 - pip
 - ray-default
 - grpcio=1.43
 - fn
 - pykalman
 - tardis-client
 - tardis-dev
 - pip:
   - -e ./
