
name: Upload to Anaconda

on:
  release:
    types: [created]

jobs:
  upload_to_anaconda:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ['linux-64', 'win-64']

    env:
      ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}

    steps:
      # Setup miniconda3
      - name: Setup miniconda3
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          auto-update-conda: true
          activate-environment: test

      # Download the corresponding artifact based on the matrix OS
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: build-${{ matrix.os }}

      # Install anaconda-client if not available in the test environment
      - name: Install Anaconda client
        run: |
          conda activate test
          if ! command -v anaconda &> /dev/null
          then
              echo "anaconda-client is not installed. Installing now..."
              conda install anaconda-client -y
          fi

      # Ensure version consistency between the GitHub release and the conda package
#      - name: Check version consistency
#        run: |
#          conda activate test
#          RELEASE_VERSION=${{ github.event.release.tag_name }}
#          PACKAGE_VERSION=$(conda inspect --extracted-info ./artifact/*.tar.bz2 | grep version)
#          if [[ "$RELEASE_VERSION" != "$PACKAGE_VERSION" ]]; then
#            echo "Error: Version mismatch between GitHub release and conda package."
#            exit 1
#          fi

      # Uploading to Anaconda
      - name: Upload to Anaconda
        run: |
          conda activate test
          anaconda upload *.tar.bz2
